---
name: Renovate

"on":
  schedule:
    # Run every Monday at 6:00 AM UTC
    - cron: "0 6 * * 1"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "info"
        type: choice
        options:
          - info
          - debug
          - trace

env:
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
