---
name: Update Semaphore Version

"on":
  schedule:
    # Check for new releases daily at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch: {}
  # Allow manual triggering

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest Semaphore version
        id: semaphore-version
        run: |
          LATEST_VERSION=$(curl -s \
            https://api.github.com/repos/semaphoreui/semaphore/releases/latest \
            | jq -r .tag_name | sed 's/^v//')
          echo "latest=$LATEST_VERSION" >> $GITHUB_OUTPUT

          # Get current version from Dockerfile
          CURRENT_VERSION=$(grep "ARG SEMAPHORE_VERSION=" semaphore/Dockerfile \
            | cut -d'=' -f2)
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          echo "Latest version: $LATEST_VERSION"
          echo "Current version: $CURRENT_VERSION"

      - name: Update Dockerfile if new version available
        id: update-dockerfile
        if: steps.semaphore-version.outputs.latest != steps.semaphore-version.outputs.current
        run: |
          LATEST_VERSION="${{ steps.semaphore-version.outputs.latest }}"
          CURRENT_VERSION="${{ steps.semaphore-version.outputs.current }}"

          # Update the Dockerfile
          sed -i "s/ARG SEMAPHORE_VERSION=$CURRENT_VERSION/ARG SEMAPHORE_VERSION=$LATEST_VERSION/" semaphore/Dockerfile

          echo "updated=true" >> $GITHUB_OUTPUT
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update-dockerfile.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Semaphore to version ${{ steps.update-dockerfile.outputs.version }}"
          title: "Update Semaphore to version ${{ steps.update-dockerfile.outputs.version }}"
          body: |
            This PR automatically updates Semaphore from version
            ${{ steps.semaphore-version.outputs.current }} to
            ${{ steps.update-dockerfile.outputs.version }}.

            **Changes:**
            - Updated `SEMAPHORE_VERSION` in `semaphore/Dockerfile`

            **Release Notes:**
            See [Semaphore releases] for details:
            https://github.com/semaphoreui/semaphore/releases/tag/v${{ steps.update-dockerfile.outputs.version }}
          branch: update-semaphore-${{ steps.update-dockerfile.outputs.version }}
          delete-branch: true

      - name: Auto-merge PR
        if: steps.update-dockerfile.outputs.updated == 'true'
        run: |
          # Wait a moment for the PR to be created
          sleep 10

          # Get the PR number
          PR_NUMBER=$(gh pr list --state open \
            --head update-semaphore-${{ steps.update-dockerfile.outputs.version }} \
            --json number --jq '.[0].number')

          if [ "$PR_NUMBER" != "null" ] && [ "$PR_NUMBER" != "" ]; then
            echo "Auto-merging PR #$PR_NUMBER"
            gh pr merge $PR_NUMBER --merge --auto
          else
            echo "Could not find PR to merge"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
