---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
