---
name: Semaphore
version: dev
slug: semaphore
description: Semaphore add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-semaphore
codenotary: contact@pedrol.me
init: false
arch:
  - aarch64
  - amd64
ports:
  3112/tcp: 3112
ports_description:
  3112/tcp: Web Interface
hassio_api: true
host_network: true
map:
  - addon_config:rw
  - ssl
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  db_type: sqlite
  public_url: ""
schema:
  ssl: bool
  certfile: str
  keyfile: str
  db_type: list(sqlite|postgresdb|mysqldb)
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  public_url: str?
  db_name: str?
  db_host: str?
  db_port: port?
  db_user: str?
  db_password: str?
